name: 'Automatic flag clean up for FeaturesFlow'
description: 'A GitHub Action to automatically remove stale feature flags in the codebase.'
author: 'Jakub Baginski'
icon: 'terminal'
color: 'gray-dark'

inputs:
  directory:
    description: 'Directory to search for files'
    required: true
    default: './src'
  auth_key:
    description: 'Authentication Key'
    required: true
    secret: true
  base_branch:
    description: 'Base branch to compare against'
    required: false
    default: 'main'

runs:
  using: 'node16'
  steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v3

    - name: 'Setup Node.js'
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: 'Install dependencies'
      run: npm install
      shell: bash

    - name: 'Run TypeScript Action'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx ts-node src/index.ts
      shell: bash

permissions:
  contents: write
